import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { Review } from '../../models/Review';

@Component({
  selector: 'app-view-reviews',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './view-reviews.component.html',
  styleUrl: './view-reviews.component.css'
})
export class ViewReviewsComponent {
  @Input() reviews: Review[] = [ {
    id: 1,
    ride: {
      idRide: 101,
      depart: 'Tunis',
      destination: 'Sousse',
      dateRide: new Date('2024-12-15T08:30:00'),
      status :"Terminé",
      driver: {
        idUser: 1,
        firstName: 'Amine',
        lastName: 'Mahmoudi',
        email: 'amine.mahmoudi@example.com',
        password: 'password123',
        address: 'Tunis, Tunisia',
        phone: '12345678',
      },
      price: 20,
      places: 3,
      description: 'Comfortable car, friendly driver.',
    },
    reviewer: {
      idUser: 2,
      firstName: 'Fatma',
      lastName: 'Ben Ali',
      email: 'fatma.benali@example.com',
      password: 'password123',
      address: 'Ariana, Tunisia',
      phone: '87654321',
    },
    reviewed: {
      idUser: 1,
      firstName: 'Amine',
      lastName: 'Mahmoudi',
      email: 'amine.mahmoudi@example.com',
      password: 'password123',
      address: 'Tunis, Tunisia',
      phone: '12345678',
    },
    dateReview: new Date('2024-12-09T10:00:00'),
    review: 5,
    comment: 'Excellent driver! The trip was smooth and enjoyable. Excellent driver! The trip was smooth and enjoyable.Excellent driver! The trip was smooth and enjoyable.Excellent driver! The trip was smooth and enjoyable.',
  },
  {
    id: 2,
    ride: {
      idRide: 102,
      depart: 'Sfax',
      destination: 'Monastir',
      dateRide: new Date('2024-12-20T14:00:00'),
      status :"Terminé",
      driver: {
        idUser: 3,
        firstName: 'Khaled',
        lastName: 'Trabelsi',
        email: 'khaled.trabelsi@example.com',
        password: 'password123',
        address: 'Sfax, Tunisia',
        phone: '12312345',
      },
      price: 25,
      places: 2,
      description: 'Spacious car with air conditioning.',
    },
    reviewer: {
      idUser: 4,firstName: 'Salma',
      lastName: 'Jemaa',
      email: 'salma.jemaa@example.com',
      password: 'password123',
      address: 'Gabes, Tunisia',
      phone: '78945612',
    },
    reviewed: {
      idUser: 3,
      firstName: 'Khaled',
      lastName: 'Trabelsi',
      email: 'khaled.trabelsi@example.com',
      password: 'password123',
      address: 'Sfax, Tunisia',
      phone: '12312345',
    },
    dateReview: new Date('2024-12-10T16:00:00'),
    review: 4,
    comment: 'Very professional driver, but the car could have been cleaner.',
  },
  {
    id: 3,
    ride: {
      idRide: 103,
      depart: 'Gabes',
      destination: 'Tunis',
      dateRide: new Date('2024-12-18T09:00:00'),
      status :"Terminé",
      driver: {
        idUser: 5,
        firstName: 'Mehdi',
        lastName: 'Bouazizi',
        email: 'mehdi.bouazizi@example.com',
        password: 'password123',
        address: 'Gabes, Tunisia',
        phone: '65432178',
      },
      price: 30,
      places: 1,
      description: 'Safe and experienced driver, with snacks provided.',
    },
    reviewer: {
      idUser: 6,
      firstName: 'Rania',
      lastName: 'Hammami',
      email: 'rania.hammami@example.com',
      password: 'password123',
      address: 'Nabeul, Tunisia',
      phone: '96385247',
    },
    reviewed: {
      idUser: 5,
      firstName: 'Mehdi',
      lastName: 'Bouazizi',
      email: 'mehdi.bouazizi@example.com',
      password: 'password123',
      address: 'Gabes, Tunisia',
      phone: '65432178',
    },
    dateReview: new Date('2024-12-11T12:00:00'),
    review: 3,
    comment: 'The driver was friendly, but the ride was delayed by an hour.',
  },
  {
    id: 2,
    ride: {
      idRide: 102,
      depart: 'Sfax',
      destination: 'Monastir',
      dateRide: new Date('2024-12-20T14:00:00'),
      status :"Terminé",
      driver: {
        idUser: 3,
        firstName: 'Khaled',
        lastName: 'Trabelsi',
        email: 'khaled.trabelsi@example.com',
        password: 'password123',
        address: 'Sfax, Tunisia',
        phone: '12312345',
      },
      price: 25,
      places: 2,
      description: 'Spacious car with air conditioning.',
    },
    reviewer: {
      idUser: 4,firstName: 'Salma',
      lastName: 'Jemaa',
      email: 'salma.jemaa@example.com',
      password: 'password123',
      address: 'Gabes, Tunisia',
      phone: '78945612',
    },
    reviewed: {
      idUser: 3,
      firstName: 'Khaled',
      lastName: 'Trabelsi',
      email: 'khaled.trabelsi@example.com',
      password: 'password123',
      address: 'Sfax, Tunisia',
      phone: '12312345',
    },
    dateReview: new Date('2024-12-10T16:00:00'),
    review: 4,
    comment: 'Very professional driver, but the car could have been cleaner.',
  },
  {
    id: 2,
    ride: {
      idRide: 102,
      depart: 'Sfax',
      destination: 'Monastir',
      dateRide: new Date('2024-12-20T14:00:00'),
      status :"Terminé",
      driver: {
        idUser: 3,
        firstName: 'Khaled',
        lastName: 'Trabelsi',
        email: 'khaled.trabelsi@example.com',
        password: 'password123',
        address: 'Sfax, Tunisia',
        phone: '12312345',
      },
      price: 25,
      places: 2,
      description: 'Spacious car with air conditioning.',
    },
    reviewer: {
      idUser: 4,firstName: 'Salma',
      lastName: 'Jemaa',
      email: 'salma.jemaa@example.com',
      password: 'password123',
      address: 'Gabes, Tunisia',
      phone: '78945612',
    },
    reviewed: {
      idUser: 3,
      firstName: 'Khaled',
      lastName: 'Trabelsi',
      email: 'khaled.trabelsi@example.com',
      password: 'password123',
      address: 'Sfax, Tunisia',
      phone: '12312345',
    },
    dateReview: new Date('2024-12-10T16:00:00'),
    review: 4,
    comment: 'Very professional driver, but the car could have been cleaner.Excellent driver! The trip was smooth and enjoyable.Excellent driver! The trip was smooth and enjoyable.Excellent driver! The trip was smooth and enjoyable.Excellent driver! The trip was smooth and enjoyable.Excellent driver! The trip was smooth and enjoyable.Excellent driver! The trip was smooth and enjoyable.',
  },
  {
    id: 2,
    ride: {
      idRide: 102,
      depart: 'Sfax',
      destination: 'Monastir',
      dateRide: new Date('2024-12-20T14:00:00'),
      status :"Terminé",
      driver: {
        idUser: 3,
        firstName: 'Khaled',
        lastName: 'Trabelsi',
        email: 'khaled.trabelsi@example.com',
        password: 'password123',
        address: 'Sfax, Tunisia',
        phone: '12312345',
      },
      price: 25,
      places: 2,
      description: 'Spacious car with air conditioning.',
    },
    reviewer: {
      idUser: 4,firstName: 'Salma',
      lastName: 'Jemaa',
      email: 'salma.jemaa@example.com',
      password: 'password123',
      address: 'Gabes, Tunisia',
      phone: '78945612',
    },
    reviewed: {
      idUser: 3,
      firstName: 'Khaled',
      lastName: 'Trabelsi',
      email: 'khaled.trabelsi@example.com',
      password: 'password123',
      address: 'Sfax, Tunisia',
      phone: '12312345',
    },
    dateReview: new Date('2024-12-10T16:00:00'),
    review: 4,
    comment: 'Very professional driver, but the car could have been cleaner.',
  },
];
}
